// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCidFHFZ36TKktOO3yqN2BoB2pJNdFZt9Y',
    appId: '1:602565405824:web:011f16ce1e796f64bc4a65',
    messagingSenderId: '602565405824',
    projectId: 'aplikasi-5b892',
    authDomain: 'aplikasi-5b892.firebaseapp.com',
    storageBucket: 'aplikasi-5b892.appspot.com',
    measurementId: 'G-CTDZ4CCRVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bl_5Elm2kBGXmEg_voI6wl-cUk2clyU',
    appId: '1:602565405824:android:063b6c0d9aa6dc93bc4a65',
    messagingSenderId: '602565405824',
    projectId: 'aplikasi-5b892',
    storageBucket: 'aplikasi-5b892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwoAkYYhx_s_XJWbhpjnaSGbLyKzy0l4',
    appId: '1:602565405824:ios:275d4172674dea9cbc4a65',
    messagingSenderId: '602565405824',
    projectId: 'aplikasi-5b892',
    storageBucket: 'aplikasi-5b892.appspot.com',
    iosClientId: '602565405824-dsdc6np2uf8sqg5om751b7iliuvteii8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwoAkYYhx_s_XJWbhpjnaSGbLyKzy0l4',
    appId: '1:602565405824:ios:275d4172674dea9cbc4a65',
    messagingSenderId: '602565405824',
    projectId: 'aplikasi-5b892',
    storageBucket: 'aplikasi-5b892.appspot.com',
    iosClientId: '602565405824-dsdc6np2uf8sqg5om751b7iliuvteii8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFinal',
  );
}
